### ISSUE TITLE
大佬,可否实现画板组件生成可访问的静态html代码呢？

### ISSUE THREAD

**Issue by sharkfly666** [OXOYO/X-Page-Editor-Vue#2]
大佬,可否实现画板组件生成可访问的静态html代码呢？

**Comment by OXOYO** [comment]
画板？咋画

**Comment by sharkfly666** [comment]
> 画板？咋画

画板只是说的是大佬的Canvas组件，借用大佬的代码进行了二次开发。感谢大佬无私奉献。

**Comment by OXOYO** [comment]
> > 画板？咋画
> 
> 画板只是说的是大佬的Canvas组件，借用大佬的代码进行了二次开发。感谢大佬无私奉献。

了解，目前没有遇到这样的使用场景。

**Comment by sharkfly666** [comment]
> > > 画板？咋画
> > 
> > 
> > 画板只是说的是大佬的Canvas组件，借用大佬的代码进行了二次开发。感谢大佬无私奉献。
> 
> 了解，目前没有遇到这样的使用场景。

大佬的开源项目还是有一定的商用需求的，很多活动h5的开发，实际上研发都更愿意让运营自己拖拖拽着就生成h5了不需要研发每次去开发。

**Comment by OXOYO** [comment]
> > > > 画板？咋画
> > > 
> > > 
> > > 画板只是说的是大佬的Canvas组件，借用大佬的代码进行了二次开发。感谢大佬无私奉献。
> > 
> > 
> > 了解，目前没有遇到这样的使用场景。
> 
> 大佬的开源项目还是有一定的商用需求的，很多活动h5的开发，实际上研发都更愿意让运营自己拖拖拽着就生成h5了不需要研发每次去开发。
嗯，目前该项目处于暂停状态，主要是由于需求不够明确，使用场景不清晰，后续需求能够明确后会考虑继续开发，如果有什么好的想法还请提出来。
